name: 'VnFilesAction'
description: 'Upload files to Azure'
author: 'Vendanor'

inputs:
  azure-token:
    required: true
    description: 'Your azure token'
  azure-account-name:
    required: false
    description: 'Azure account name'
    default: 'vnproductionstoragev2'
  salt:
    required: true
    description: 'Add some salt'
  input:
    required: true
    description: 'Source filename you want to upload'
  append-md5-hash:
    required: false
    description: 'Apply md5 hash at to target filename'
    default: true

outputs:
  filename:
    description: 'Uploaded filename'

runs:
  using: 'node12'
  main: 'dist/index.js'
